config/routes.rb
Rails.application.routes.draw do
  root 'jobs#index'

  get '/:hashid', to: 'job_applicants#show', as: :job_applicant_hashid
  get '/:hashid/edit', to: 'job_applicants#edit', as: :job_applicant_hashid_edit
  get '/:hashid/new', to: 'job_applicants#new', as: :job_applicant_hashid_new
  get '/:hashid/create', to: 'job_applicants#create', as: :job_applicant_hashid_create

  post '/subscribers/create', to: 'subscribers#create'
  get '/jobs/new', to: 'jobs#new'
  get '/jobs/:hashid', to: 'jobs#show', as: :job_hashid
  get '/jobs/:hashid/destroy', to: 'jobs#destroy', as: :destroy
  get '/myjobs', to: 'jobs#poster_jobs'
  devise_for :posters
  devise_for :job_applicants
  resources :jobs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  include Hashid::Rails

  has_one :poster
  has_many :job_applications

  validates :title, presence: true
  validates :location, presence: true
  validates :description, presence: true

  has_rich_text :description

  def to_param
    hashid
  end
end

app/models/job_applicant.rb
class JobApplicant < ApplicationRecord
  include Hashid::Rails

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :name, presence: true
  validates :email, presence: true, email: true

  has_many :job_applications

  def to_param
    hashid
  end
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :JobApplicant
  belongs_to :Job
end

app/models/poster.rb
class Poster < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :jobs
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true, email: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/job_applicants_controller.rb
class JobApplicantsController < ApplicationController
  before_action :authenticate_job_applicant!

  def show
    @job_applicant = JobApplicant.find_by_hashid params[:job_applicant_hashid]
  end

  def edit
    @job_applicant = JobApplicant.find(params[:id])
  end

  def new
    @job_applicant = JobApplicant.new
  end

  def create
    @job_applicant = JobApplicant.create(job_applicant_params)
    if @job_applicant.save
      redirect_to @jjob_applicantob
    else
      redirect_back fallback_location: @job_applicant
      flash[:alert] = 'Check the details provided! Something is wrong!'
    end
  end

  def update
    @job_applicant = Job.find params[:id]
    if @job_applicant.update(job_params)
      redirect_to @job_applicant
    else
      redirect_back fallback_location: @job_applicant
      flash[:alert] = 'Check the job details provided! Something is wrong!'
    end
  end

  private
    def job_applicant_params
      params.require(:job_applicant).permit(:name, :email, :resume)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_poster!, except: [:show, :index]

  def index
    @jobs = Job.all.with_rich_text_description.order(created_at: :desc)
  end

  def show
    @job = Job.find(params[:hashid])
  end

  def new
    @job = Job.new
  end

  def create
    @job = current_poster.jobs.build(job_params)
    if @job.save
      redirect_to @job
    else
      redirect_back fallback_location: @job
      flash[:alert] = 'Check the job details provided! Something is wrong!'
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find params[:id]
    if @job.update(job_params)
      redirect_to @job
    else
      redirect_back fallback_location: @job
      flash[:alert] = 'Check the job details provided! Something is wrong!'
    end
  end

  def destroy
    @job = Job.find params[:job_hashid]
    @job.destroy
    redirect_to myjobs_url
  end

  def poster_jobs
    @jobs = current_poster.jobs
  end

  private
    def job_params
      params.require(:job).permit(:title, :location, :description, :salary, :job_type)
    end
end

app/controllers/subscriber_controller.rb
class SubscriberController < ApplicationController
  def new
    @subscriber = Subscriber.new
  end

  def create
    @subscriber = Subscriber.create(subscriber_params)
    if @subscriber.save
      redirect_back fallback_location: @subscriber
      flash[:notice] = 'Okay! Rocky will meow job recommendations at you from time to time!'
  end

  def destroy
    @subscriber = Subscriber.find(params[:id])
    redirect_to root_path if @group.destroy
  end

  private
    def subscriber_params
      params.require(:subscriber).permit(:email)
    end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def new
    @subscriber = Subscriber.new
  end

  def create
    @subscriber = Subscriber.create(subscriber_params)
    if @subscriber.save
      redirect_to root_path
      flash[:notice] = 'Okay! Rocky will meow you job recommendations at you from time to time!'
    else
      redirect_to root_path
      flash[:notice] = 'Oh! You forgot to tell me you email.'
    end
  end

  def destroy
    @subscriber = Subscriber.find(params[:id])
    redirect_to root_path if @group.destroy
  end

  private
    def subscriber_params
      params.permit(:email)
    end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def greet
    if current_page?(root_path)
      render 'layouts/greet'
    end
  end

  def what_nav
    if poster_signed_in?
      render 'layouts/poster-nav'
    elsif job_applicant_signed_in?
      render 'layouts/job-applicant-nav'
    else
      render 'layouts/default-nav'
    end
  end

  def is_current_user_applicant?
    if job_applicant_signed_in?
      link_to 'MY PROFILE', job_applicant_hashid_path(current_job_applicant), class: 'actions-link hover:underline block'
    else
      link_to 'JOB SEEKERS', new_job_applicant_registration_url, class: 'actions-link hover:underline block'
    end
  end
end

app/helpers/job_applicant_helper.rb
module JobApplicantHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/helpers/subscriber_helper.rb
module SubscriberHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/job_applicants/create.html.erb
<h1>JobApplicant#create</h1>
<p>Find me in app/views/job_applicant/create.html.erb</p>

app/views/job_applicants/edit.html.erb
<h1>JobApplicant#edit</h1>
<p>Find me in app/views/job_applicant/edit.html.erb</p>

app/views/job_applicants/index.html.erb
<h1>JobApplicant#index</h1>
<p>Find me in app/views/job_applicant/index.html.erb</p>

app/views/job_applicants/new.html.erb
<h1>JobApplicant#new</h1>
<p>Find me in app/views/job_applicant/new.html.erb</p>

app/views/job_applicants/show.html.erb
<div class="bg-white p-2 rounded-lg shadow-lg">
  
</div>

app/views/jobs/_edit-job.html.erb
<div class="flex">
    <div class="mr-1"><%= link_to "Delete", job, method: :delete, class: "no-underline hover:underline text-blue" %></div>
    <div class="ml-1"><%= link_to "Edit", edit_job_path(job), class: "no-underline hover:underline text-blue" %></div>
</div>

app/views/jobs/_form.html.erb
<%= turbo_frame_tag :jobs do %>
<div class="flex flex-col justify-center items-center mb-6">
    <% flash.each do |type, msg| %>
    <div class="bg-green-100 border-2 border-green-500 text-green-700 flex align-items rounded-lg" role="alert">
        <div class="p-4">
            <p id="flash-message"><%= msg %></p>
        </div>
    </div>
    <% end %>
</div>
<%= form_with model: job do |f| %>
<div class="flex flex-col py-6">
    <div class="grid grid-cols-1 py-4">
        <div>
            <%= f.text_field :title, autofocus: true, autocomplete: "name", class: 'shadow appearance-none border rounded w-80 py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', placeholder: 'Job Title' %>
            <%= f.text_field :location, autofocus: true, autocomplete: "name", class: 'py-2 shadow appearance-none border rounded w-80 py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', placeholder: 'Location' %>
            <%= f.text_field :salary, autofocus: true, autocomplete: "name", class: 'py-2 shadow appearance-none border rounded w-80 py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', placeholder: 'Salary' %>
            <%= f.text_field :job_type, autofocus: true, autocomplete: "name", class: 'py-2 shadow appearance-none border rounded w-80 py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', placeholder: 'Job Type' %>
        </div>
    </div>
    <%= f.rich_text_area :description, autofocus: true, autocomplete: "name", class: 'shadow appearance-none border rounded w-full h-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', placeholder: 'Job Description' %>
    <%= f.submit "Post!", class: "primary-btn rounded mt-4 p-2 md:p-2 hover:border-lg" %>
</div>
<% end %>
<% end %>

app/views/jobs/_job-post.html.erb
<div class="bg-white p-1 rounded-lg shadow-lg">
    <div class="flex justify-between">
        <div class="details flex">
            <div class="image">
                <%= image_tag 'company.svg', class: "w-14 h-14 p-2 md:w-20 md:h-20" %>
            </div>
            <div class="job-details flex flex-col justify-center">
                <div class="job-details-title text-4xl font-semibold">
                    <%= job.title %>
                </div>
                <div class="job-details-addendum">
                    <small class="sm:text-opacity-text-50 md:text-opacity-50"><%= job.location %> | <%= job.job_type %> | <%= job.salary %></small>
                </div>
            </div>
        </div>
        <% if poster_signed_in? %>
        <div class="flex">
        <div class="flex poster-edit px-2">
            <div class="primary-btn p-6 rounded-lg"><%= link_to "Edit This Job", edit_job_path(job), class: 'font-semibold' %></div>
        </div>
        <div class="flex poster-delete px-2">
            <div class="primary-btn p-6 rounded-lg"><%= link_to "Delete This Job", destroy_url(job), class: 'font-semibold', id: 'delete-job' %></div>
        </div>
        </div>
        <% else %>
        <div class="flex apply-button px-2" data-controller="applier">
          <div id="apply-btn" class="primary-btn p-6 rounded-lg font-semibold" data-action="click->applier#applyToJob">Apply</div>
        </div>
        <% end %>
    </div>
    <hr />
    <div class="job-description p-4">
        <%= job.description %>
    </div>
</div>

app/views/jobs/_job.html.erb
<div class="bg-white p-2 rounded-lg shadow-lg flex transition duration-300 ease-in-out transform hover:-translate-y-1">
  <%= image_tag 'company.svg', class: "w-14 h-14 p-2 md:w-20 md:h-20" %>
  <div class="flex flex-col justify-center">
    <%= link_to job.title, job, class: "no-underline hover:underline text-blue" %>
    <small class="sm:text-opacity-text-50 md:text-opacity-50"><%= job.location %> | <%= job.job_type %> | <%= job.salary %></small>
  </div>
</div>

app/views/jobs/_rss-subscribe.html.erb
<%= turbo_frame_tag :subscribers do %>
<div class="bg-white p-4 rounded-lg shadow-lg" id="subscriber">
  <div class="flex justify-center p-2" data-controller="subscriber">
    <h3 class="text-center text-2xl font-semibold pr-3">Subscribe to Worksite Rocks' RSS feed!</h3>
    <div class="close-rss-subscriber pl-5" data-action="click->subscriber#removeSubscriber">X</div>
  </div>
  <div class="flex align-items justify-center">
    <div class="image flex align-items">
      <%= image_tag 'wolf.svg', class: "md:w-40 md:h-40" %>
    </div>
    <%= form_with url: "/subscribers/create" do |f| %>
      <div class="justify-center items-center pt-10 pr-10 pb-10 pl-3">
        <%= f.email_field :email, autofocus: false, autocomplete: "email", class: 'shadow appearance-none border rounded w-80 md:w-40 py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', placeholder: 'rocky@rocks.com' %>
        <%= f.submit "Send me jobs!", class: "primary-btn rounded mt-4 p-2 md:p-2" %>
      </div>
    <% end %>
  </div>
  <div class="flex flex-col justify-center items-center" data-controller="subscriber">
    <% flash.each do |type, msg| %>
      <div class="bg-green-100 border-2 border-green-500 text-green-700 flex align-items rounded-lg" role="notice">
        <div class="p-4">
          <p id="flash-message"><%= msg %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/jobs/edit.html.erb
<div class="bg-white p-4 rounded-lg shadow-lg">
    <div class="text-4xl m-y-4">Edit Job Posting</div>
    <%= render 'form', job: @job %>
</div>

app/views/jobs/index.html.erb
<div class="grid grid-cols-1 md:grid-cols-2 gap-x-4" id="job-roster">
  <div class="job-list grid grid-cols-1 gap-y-4">
    <%= render @jobs %>
  </div>
  <div class="rss-subscribe hidden md:block">
    <%= render 'rss-subscribe', subscriber: @subscriber %>
  </div>
</div>

app/views/jobs/poster_jobs.html.erb
<div class="grid grid-cols-1 gap-x-4">
  <%= render @jobs %>
</div>

app/views/jobs/show.html.erb
<%= render 'job-post', job: @job %>

app/views/layouts/_default-nav.html.erb
<nav class="flex flex-col justify-between p-4 nav-color mr-0 sticky top-0 z-50 w-100">
  <div class="title-actions flex justify-between">
    <div class="wsr-identity transition duration-300 ease-in-out transform hover:translate-x-1 p-4">
      <%= link_to "Worksite Rocks!", root_path, class: "wsr-identity-link text-2xl md:text-5xl" %>
    </div>
    <div class="image block md:hidden">
      <%= image_tag "wolf.svg", size: "80x80" %>
    </div>
    <div class="actions flex align-items">
      <li class="hidden md:block p-2 m-3 flex align-items job-seekers rounded-lg content-center transition duration-300 ease-in-out transform hover:-translate-x-1">
        <%= is_current_user_applicant? %>
      </li>
      <li class="hidden md:block p-2 m-3 flex align-items primary-btn rounded-lg content-center transition duration-300 ease-in-out transform hover:-translate-x-1">
        <%= link_to "POST A JOB!", new_job_path, class: "actions-link hover:underline block" %>
      </li>
    </div>
  </div>
</nav>
<div class="hidden md:flex justify-center p-10 booster">
  <div class="image">
    <%= image_tag "wolf.svg", size: "200x200" %>
  </div>
  <div class="catch flex align-items p-10">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eget nisi quis purus porta tincidunt. Nam condimentum bibendum sapien nec venenatis</p>
  </div>
</div>

app/views/layouts/_greet.html.erb
<div class="container p-auto m-auto">
  <div class="text-xl md:text-2xl font-extrabold p-6 m-auto text-center greet-text">
    Find Tech and Marketing Jobs!
  </div>
</div>

app/views/layouts/_job-applicant-nav.html.erb
<nav class="flex flex-col justify-between p-4 nav-color mr-0 sticky top-0 z-50 w-100">
  <div class="title-actions flex justify-between">
    <div class="wsr-identity transition duration-300 ease-in-out transform hover:translate-x-1 p-4">
      <%= link_to "Worksite Rocks!", root_path, class: "wsr-identity-link text-2xl md:text-5xl" %>
    </div>
    <div class="image block md:hidden">
      <%= image_tag "wolf.svg", size: "80x80" %>
    </div>
    <div class="actions flex align-items">
      <li class="hidden md:block p-2 m-3 flex align-items job-seekers rounded-lg content-center transition duration-300 ease-in-out transform hover:-translate-x-1">
        <%= link_to "LOGOUT", destroy_job_applicant_session_url, method: :delete, class: "actions-link hover:underline block" %>
      </li>
      <li class="hidden md:block p-2 m-3 flex align-items job-seekers rounded-lg content-center transition duration-300 ease-in-out transform hover:-translate-x-1">
        <%= link_to "MY APPLICATIONS", myjobs_url, class: "actions-link hover:underline block" %>
      </li>
    </div>
  </div>
</nav>

app/views/layouts/_poster-nav.html.erb
<nav class="flex flex-col justify-between p-4 nav-color mr-0 sticky top-0 z-50 w-100">
  <div class="title-actions flex justify-between">
    <div class="wsr-identity transition duration-300 ease-in-out transform hover:translate-x-1 p-4">
      <%= link_to "Worksite Rocks!", root_path, class: "wsr-identity-link text-2xl md:text-5xl" %>
    </div>
    <div class="image block md:hidden">
      <%= image_tag "wolf.svg", size: "80x80" %>
    </div>
    <div class="actions flex align-items">
      <li class="hidden md:block p-2 m-3 flex align-items job-seekers rounded-lg content-center transition duration-300 ease-in-out transform hover:-translate-x-1">
        <%= link_to "LOGOUT", destroy_poster_session_path, method: :delete, class: "actions-link hover:underline block" %>
      </li>
      <li class="hidden md:block p-2 m-3 flex align-items job-seekers rounded-lg content-center transition duration-300 ease-in-out transform hover:-translate-x-1">
        <%= link_to "MY JOBS", myjobs_url, class: "actions-link hover:underline block" %>
      </li>
      <li class="hidden md:block p-2 m-3 flex align-items primary-btn rounded-lg content-center transition duration-300 ease-in-out transform hover:-translate-x-1">
        <%= link_to "POST A JOB!", new_job_path, class: "actions-link hover:underline block" %>
      </li>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WsR! | Find Jobs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Train+One&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= what_nav %>
    <%= greet %>
    <div class="p-2 md:p-8 w-screen h-screen">
      <div class="grid grid-cols-1 gap-y-2 gap-x-4">
        <%= yield %>
      </div>
    </div>
    <% if false %>
    <% if !request.path.include?('/jobs/new') %>
      <div class="footer booster sticky bottom-0">
        <div class="copyright text-center p-6">© <%= Time.zone.now.year %> worksite.rocks - All Rights Reserved</div>
      </div>
    <% end %>
    <% end %>
  </body>
</html>